# Setup
title:               Project Night Azalea
tagline:             ''
description:         'Host for walk-throughs and presentation for the Youtube Channel [TBD](https://youtube.com/)'
url:                 https://fivebluepetals.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Valerie Wang
  url:               https://github.com/fivebluepetals
  email:             valerielle.wang@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
